stages:
    - apps

API:
    stage: apps
    trigger:
        include: apps/api/.gitlab-ci.yml
        strategy: depend
    # rules:
    #     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #     - changes:
    #         - apps/api/**/*

Front:
    stage: apps
    trigger:
        include: apps/front/.gitlab-ci.yml
        strategy: depend
    # rules:
    #     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    #     - changes:
    #         - apps/front/**/*
