version: '3'
services:
    web:
        container_name: boiler-nginx
        build:
            context: ./apps/nginx
            dockerfile: Dockerfile
        volumes:
            - ./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./apps/api:/var/www
        ports:
            - 8700:80
        restart: always
        depends_on:
            - php
        networks:
            - php-net
    php:
        container_name: boiler-php
        build:
            context: ./apps/api
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./apps/.php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./apps/.php-ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./apps/api:/var/www
        links:
            - dbpostgres
        networks:
            - php-net
            - data-net

    dbpostgres:
        container_name: boiler-postgres
        build:
            context: ./apps/database/postgres
            dockerfile: Dockerfile
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: boiler_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        ports:
            - "5432:5432"
        networks:
            - data-net
        

    pgadmin:
        container_name: boiler-pgadmin
        build:
            context: ./apps/database/pgadmin
            dockerfile: Dockerfile
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        links:
            - "dbpostgres:pgsql-server"
        environment:
            PGADMIN_DEFAULT_EMAIL: user@boiler.com
            PGADMIN_DEFAULT_PASSWORD: pass
            PGADMIN_LISTEN_PORT: 80
        restart: always
        ports:
            - "8732:80"
        tty: true

    front:
      container_name: boiler-front
      build:
        context: apps/front
        dockerfile: Dockerfile
      volumes:
        - './apps/front:/usr/src/app:rw'
      ports:
        - '3000:3000'
      restart: unless-stopped


networks:
    php-net:
    data-net:

volumes:
    pg_data:
    pgadmin_data:
