image: jakzal/phpqa:php8.1

before_script:
    - cd apps/api
    - composer install

cache:
    paths:
        - vendor/

stages:
    - Security
    - CodingStandards
    - Tests

security-checker:
    stage: Security
    script:
        - local-php-security-checker composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/kernel.php ./src
    allow_failure: true

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./src
    allow_failure: true

unit-tests:
    stage: Tests
    script:
        - bin/phpunit tests/Unit --testdox
    allow_failure: true

functional-tests:
    stage: Tests
    services:
        - name: postgres
          alias: pg
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        DATABASE_URL: 'postgresql://user:pass@pg:5432/test_db?serverVersion=14&charset=utf8'
    before_script:
        - cd apps/api
        - apt-get update && apt-get install -y libpq-dev
        - docker-php-ext-install pdo pdo_pgsql pgsql
        - composer require symfony/runtime
        - php bin/console doctrine:database:drop --if-exists --force --env=test
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:schema:update --force --env=test --no-interaction
    script:
        - bin/phpunit tests/Func --testdox
    allow_failure: true
